Added delta threshold and changed coverage threshold to 80 to test - added failure reasons

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -50,6 +50,9 @@ steps:
       echo "Get cloud build project configuration values"
       source .env.cloud_build 
 
+      # Instantiate a failure reasons array
+      failure_reasons=()
+
       echo "Copy test coverage report from docker volume to a google cloud storage bucket."
       timestamp=$(date +%s)
       gsutil cp ./coverage/coverage.json "gs://${TEST_COVERAGE_BUCKET_NAME}/${BRANCH_NAME}/${timestamp}-${COMMIT_SHA}.json"
@@ -88,28 +91,54 @@ steps:
       fi
       
       echo ""
-      echo "Test coverage threshold: ${TEST_COVERAGE_THRESHOLD}%"
-      echo "This commit: ${this_commit_coverage}%"
-      echo "GitHub main or master last commit: ${last_github_deployment_branch_coverage}%"
-      echo "Coverage difference: ${coverage_difference}%"
+      echo "threshold: ${TEST_COVERAGE_THRESHOLD}%"
+      echo ""
+      echo "this commit: ${this_commit_coverage}%"
+      echo "last main or master commit: ${last_github_deployment_branch_coverage}%"
+      echo "------------------------------------------"
+      echo "difference between this commit and last on main or master: ${coverage_difference}%"
       echo ""
 
-      # Compare total coverage to failure threshold.
+      # Compare delta 
+      if (( $(echo "${coverage_difference} < ${TEST_DELTA_THRESHOLD}" | bc -l) )); then
+        echo "Test coverage dropped (${coverage_difference}%) which is more than the delta threshold of ${TEST_DELTA_THRESHOLD}%"
+        echo "Please increase the number of unit tests."
 
+        failure_reasons+=("delta")
+      else
+        echo "Test coverage delta is within range."
+      fi
+      
+      # Compare total coverage to failure threshold.
       if (( $(echo "${this_commit_coverage} < ${TEST_COVERAGE_THRESHOLD}" | bc -l) )); then
         echo ""
         echo "Insufficent test coverage."  
-        echo "Coverage (${this_commit_coverage}%) is below the threshold of (${TEST_COVERAGE_THRESHOLD}%) - please add more unit tests!"
+        echo "Coverage (${this_commit_coverage}%) dropped below the threshold of (${TEST_COVERAGE_THRESHOLD}%) - please add more unit tests!"
         echo "For more details, read the test coverage report."
         echo ""
-        # # Fail build if main branch.
-        # if [[ "${BRANCH_NAME}" == "${GITHUB_MAIN_BRANCH_NAME}" ]]; then  
-        #   echo "Insufficent test coverage."  
-        #   exit 1
-        # fi
+
+        failure_reasons+=("below_coverage_threshold")
+
       else
         echo "Coverage (${this_commit_coverage}%) is above the threshold of ${TEST_COVERAGE_THRESHOLD}."
       fi
+
+      if [ ${#failure_reasons[@]} -eq 0 ]; then
+        echo "Test coverage is suficient  - Continuing..."
+      else
+        echo "Failed test coverage step for: "
+        for reason in "${failure_reasons[@]}"; do
+          echo "$reason"
+        done
+
+        # Fail build if not main (or master) deployment branch.
+        # if [[ "${BRANCH_NAME}" != "${GITHUB_MAIN_BRANCH_NAME}" ]]; then  
+        #   echo "Insufficent test coverage - build failed."  
+        #   exit 1
+        # fi
+      fi
+
+
 
   - id: "Build image if main"
     name: "gcr.io/cloud-builders/docker"
